@host = http://localhost:{{$dotenv PORT}}/api/compose
@Auth=Basic {{$dotenv API_USERNAME}}:{{$dotenv API_PASSWORD}}

###
POST {{host}}/
Authorization: {{Auth}}
Content-Type: application/json

{
  "name": "simple"
}

### get services
GET {{host}}/simple/service
Authorization: {{Auth}}

### create service
POST {{host}}/simple/service
Authorization: {{Auth}}
Content-Type: application/json

{
  "name": "web",
  "image": "nginx",
  "labels": {
    "mandok": "visible"
  }
}

### action
PUT {{host}}/simple/action
Authorization: {{Auth}}
Content-Type: application/json

{
  "action": "down",
  "services": []
}
