@host = {{$dotenv BASE_URL}}/api/compose
@Auth=Basic {{$dotenv API_USERNAME}}:{{$dotenv API_PASSWORD}}

### create project
POST {{host}}/hello
Authorization: {{Auth}}
Content-Type: application/json

{
  "version": "3",
  "services": {
    "web": {
      "image": "nginx",
      "labels": {
        "mandok": "visible"
      }
    },
    "webia": {
      "image": "nginx",
      "labels": {
        "mandok": "visible"
      }
    }
  }
}

### read project
GET {{host}}/hello
Authorization: {{Auth}}

### read project status
GET {{host}}/hello/status?all=true
Authorization: {{Auth}}

### delete project
DELETE {{host}}/hello
Authorization: {{Auth}}

### start project basic
POST {{host}}/hello/start?pull=true
Authorization: {{Auth}}

### start specific services in project
POST {{host}}/hello/start?service=web
Authorization: {{Auth}}

### start force restart even without update
POST {{host}}/hello/start?restart=true
Authorization: {{Auth}}

### start pull image and restart if new image pulled
POST {{host}}/hello/start?pull=true
Authorization: {{Auth}}

### stop project
POST {{host}}/hello/stop
Authorization: {{Auth}}

### route services
POST {{host}}/hello/route/webia
Authorization: {{Auth}}
Content-Type: application/json

{
  "domain": "webia.hello.local"
}

### delete route
DELETE {{host}}/hello/route/webia