@host = {{$dotenv BASE_URL}}/api/docker/containers
@Auth=Basic {{$dotenv API_USERNAME}}:{{$dotenv API_PASSWORD}}

@project = drgreenhouse
@service = app

### get all
GET {{host}}
Authorization: {{Auth}}

### get in project
GET {{host}}/{{project}}
Authorization: {{Auth}}

### get container detail
GET {{host}}/{{project}}/{{service}}
Authorization: {{Auth}}

### restart container
GET {{host}}/{{project}}/{{service}}/restart
Authorization: {{Auth}}

### restart container with image tag
GET {{host}}/{{project}}/{{service}}/restart
Authorization: {{Auth}}
Content-Type: application/json
X-Image-Tag: 82349800
