@host = {{$dotenv BASE_URL}}/api/repo
@Auth=Basic {{$dotenv API_USERNAME}}:{{$dotenv API_PASSWORD}}

@registryHost={{$dotenv REGISTRY_HOST}}
@registryUser={{$dotenv REGISTRY_USERNAME}}
@registryPass={{$dotenv REGISTRY_PASSWORD}}

### repo login
POST {{host}}/login
Authorization: {{Auth}}
Content-Type: application/json

{
  "registry": "{{registryHost}}",
  "username": "{{registryUser}}",
  "password": "{{registryPass}}"
}